on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y clang-format
      - run: clang-format --dry-run --Werror $(git ls-files '*.cpp' '*.h')
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j4
      - run: ctest --test-dir build --output-on-failure
